name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      # 3. Restaurar dependências
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build do projeto
      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      # 5. Executar testes
      - name: Run tests
        run: dotnet test --verbosity normal
